config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :faqs do 
    member do
      get :answer
    end
  end


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :feed_backs
  resources :blood_requests
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    can :manage, FeedBack
    can :manage, BloodRequest
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/blood_request.rb
class BloodRequest < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :answer, :qlabel
end

app/models/feed_back.rb
class FeedBack < ActiveRecord::Base
  attr_accessible :email, :message, :mobile, :name

  validates :email, :message, :mobile, :name, :presence => true
  validates :email, :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  validates :mobile, :length => {:minimum => 10, :maximum => 13}, :format => { :with => /\A\S[0-9\+\/\(\)\s\-]*\z/i }
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/blood_requests_controller.rb
class BloodRequestsController < ApplicationController
  load_and_authorize_resource
  layout 'www'

  def new
  end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  layout 'www', :only => [:answer]
  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faqs }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @faq = Faq.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faq }
    end
  end

  def answer
    @faq = Faq.find(params[:id])
  end

  # GET /faqs/new
  # GET /faqs/new.json
  def new
    @faq = Faq.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/1/edit
  def edit
    @faq = Faq.find(params[:id])
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(params[:faq])

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render json: @faq, status: :created, location: @faq }
      else
        format.html { render action: "new" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /faqs/1
  # PUT /faqs/1.json
  def update
    @faq = Faq.find(params[:id])

    respond_to do |format|
      if @faq.update_attributes(params[:faq])
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy

    respond_to do |format|
      format.html { redirect_to faqs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/feed_backs_controller.rb
class FeedBacksController < ApplicationController
  load_and_authorize_resource
  layout 'www'
  before_filter :load_approved_feed_backs

  def new
  	
  end

  def create
    if @feed_back.save
      flash[:notice] = "Your Experience is added and is Pending approval"
      redirect_to feed_backs_path
    else
      render :action => 'new'
    end
  end

  def index
    
  end

private

  def load_approved_feed_backs
    #Presently loading all feed backs
    @feed_backs = FeedBack.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'www'
  def index
    @users = User.all
    @faqs = Faq.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
  
end

app/helpers/blood_requests_helper.rb
module BloodRequestsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/feed_backs_helper.rb
module FeedBacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blood_requests/_form.html.haml
%h4
  Please use the form below to to Post your Required Blood Request
.form-horizontal
  = semantic_form_for @blood_request do |f|
    = f.inputs do
      .control-group
        = f.input :patient_name, :label_html => {:class => "control-label"}
      .control-group
        = f.input :reqd_blood_group, :label_html => {:class => "control-label"}
      .control-group
        = f.input :gender, :label_html => {:class => "control-label"}
      .control-group
        = f.input :age, :label_html => {:class => "control-label"}
      .control-group
        = f.input :units, :label_html => {:class => "control-label"}
      .control-group
        = f.input :landline, :label_html => {:class => "control-label"}
      .control-group
        = f.input :mobile_number, :label_html => {:class => "control-label"}
      .control-group
        = f.input :hospital_address, :label_html => {:class => "control-label"}
      .control-group
        = f.input :email, :label_html => {:class => "control-label"}
      .control-group
        = f.input :patient_address, :label_html => {:class => "control-label"}
      .control-group
        = f.input :purpose, :label_html => {:class => "control-label"}
      .control-group
        = f.input :city, :label_html => {:class => "control-label"}
    
    .form-actions
      = f.buttons do
        = f.commit_button "Save", :button_html => {:class => "btn"}

app/views/blood_requests/new.html.haml
= render 'form'

app/views/faqs/_form.html.erb
<%= simple_form_for(@faq) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :qlabel %>
    <%= f.input :answer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/faqs/answer.html.erb
<p>
  <pre><%= @faq.answer %></pre>
</p>

app/views/faqs/edit.html.erb
<h1>Editing faq</h1>

<%= render 'form' %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<h1>Listing faqs</h1>

<table>
  <tr>
    <th>Qlabel</th>
    <th>Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @faqs.each do |faq| %>
  <tr>
    <td><%= faq.qlabel %></td>
    <td><%= faq.answer %></td>
    <td><%= link_to 'Show', faq %></td>
    <td><%= link_to 'Edit', edit_faq_path(faq) %></td>
    <td><%= link_to 'Destroy', faq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Faq', new_faq_path %>

app/views/faqs/new.html.erb
<h1>New faq</h1>

<%= render 'form' %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Qlabel:</b>
  <%= @faq.qlabel %>
</p>

<p>
  <b>Answer:</b>
  <%= @faq.answer %>
</p>


<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>

app/views/feed_backs/_table.html.erb
<% if objects.any? %>
  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>email</th>
        <th>Mobile</th>
        <th>Message</th>
      </tr>
    </thead>
    <tbody>
      <% for feed_back in objects %>
        <tr class="<%= cycle :odd, :even %>">
          <td><%= feed_back.name %></td>
          <td><%= feed_back.email %></td>
          <td><%= feed_back.mobile %></td>
          <td><%= feed_back.message %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/feed_backs/index.html.erb
<%= render :partial => 'table', :locals => {:objects => @feed_backs} %>

app/views/feed_backs/new.html.haml
.form-horizontal
  = semantic_form_for @feed_back do |f|
    = f.inputs do
      .control-group
        = f.input :name, :label_html => {:class => "control-label"}
      .control-group
        = f.input :email, :label_html => {:class => "control-label"}
      .control-group
        = f.input :mobile, :label_html => {:class => "control-label"}
      .control-group
        = f.input :message, :label_html => {:class => "control-label"}
    
    .form-actions
      = f.buttons do
        = f.commit_button "Save", :button_html => {:class => "btn"}



= render :partial => 'table', :locals => {:objects => @feed_backs}

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Student Blood Donor", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/_www_navigation.html.erb
<ul class="nav nav-list">
  <li class="nav-header">Quick Links</li>
  <li class="active"><a href="#">Home</a></li>
  <li><a href="#">Register As Donor</a></li>
  <li><%= link_to 'Post Your Request', new_blood_request_path %></li>
  <li><%= link_to 'Share Experience', new_feed_back_path %></li>
  <li><a href="#">Contact Us</a></li>
  <li class="nav-header">FAQs</li>
  <% Faq.all.each do |faq| %>
    <li class="active"><%= link_to faq.qlabel, answer_faq_path(faq) %></li>
  <% end %>
  <li><a href="#">Why Donate Blood</a></li>
  <li><a href="#">Who Needs Blood</a></li>
  <li><a href="#">Tips On Donation</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails3 Bootstrap Devise Cancan" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails3 Bootstrap Devise Cancan" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/www.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails3 Bootstrap Devise Cancan" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails3 Bootstrap Devise Cancan" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= link_to "Student Blood Donor", root_path, :class => 'brand' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class='span2'>
              <%= render 'layouts/www_navigation' %>
            </div>
            <div class="span10">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
	  <thead>
      <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
          <th>Role</th>
          <th></th>
          <th></th>                                      
      </tr>
  </thead>   
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.to_date %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
          <%= render user %>
        </td>
        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>                                       
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>